{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    "from tensorflow.keras.models import load_model\n",
    "import cv2\n",
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "import mediapipe as mp\n",
    "from tensorflow.keras.models import Sequential\n",
    "from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout\n",
    "import joblib"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.\n"
     ]
    }
   ],
   "source": [
    "model = load_model('model.h5')\n",
    "# model = joblib.load('rfModel.joblib')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n"
     ]
    }
   ],
   "source": [
    "# import cv2\n",
    "# import numpy as np\n",
    "# import mediapipe as mp\n",
    "# import joblib\n",
    "\n",
    "# # Load the trained Random Forest model\n",
    "# model = joblib.load('model.h5')\n",
    "\n",
    "# Define the labels dictionary\n",
    "labels_dict = {0: 'A', 1: 'B', 2: 'C', 3: 'D', 4: 'E', 5: 'F', 6: 'G', 7: 'H', 8: 'I', 9: 'J', 10: 'K', 11: 'L', 12: 'M', 13: 'N', 14: 'O', 15: 'P', 16: 'Q', 17: 'R', 18: 'S', 19: 'T', 20: 'U', 21: 'V', 22: 'W', 23: 'X', 24: 'Y', 25: 'Z'}\n",
    "\n",
    "# Initialize MediaPipe Hands\n",
    "mp_hands = mp.solutions.hands\n",
    "mp_drawing = mp.solutions.drawing_utils\n",
    "mp_drawing_styles = mp.solutions.drawing_styles\n",
    "\n",
    "hands = mp_hands.Hands(static_image_mode=True, min_detection_confidence=0.3)\n",
    "\n",
    "# Start video capture\n",
    "cap = cv2.VideoCapture(0)\n",
    "\n",
    "while True:\n",
    "    data_aux = []\n",
    "    x_ = []\n",
    "    y_ = []\n",
    "\n",
    "    ret, frame = cap.read()\n",
    "    if not ret:\n",
    "        print(\"Failed to capture image\")\n",
    "        break\n",
    "\n",
    "    H, W, _ = frame.shape\n",
    "    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)\n",
    "    results = hands.process(frame_rgb)\n",
    "\n",
    "    if results.multi_hand_landmarks:\n",
    "        for hand_landmarks in results.multi_hand_landmarks:\n",
    "            mp_drawing.draw_landmarks(\n",
    "                frame,  # image to draw\n",
    "                hand_landmarks,  # model output\n",
    "                mp_hands.HAND_CONNECTIONS,  # hand connections\n",
    "                mp_drawing_styles.get_default_hand_landmarks_style(),\n",
    "                mp_drawing_styles.get_default_hand_connections_style())\n",
    "\n",
    "            for i in range(len(hand_landmarks.landmark)):\n",
    "                x = hand_landmarks.landmark[i].x\n",
    "                y = hand_landmarks.landmark[i].y\n",
    "\n",
    "                x_.append(x)\n",
    "                y_.append(y)\n",
    "\n",
    "            for i in range(len(hand_landmarks.landmark)):\n",
    "                x = hand_landmarks.landmark[i].x\n",
    "                y = hand_landmarks.landmark[i].y\n",
    "                data_aux.append(x - min(x_))\n",
    "                data_aux.append(y - min(y_))\n",
    "\n",
    "        x1 = int(min(x_) * W) - 10\n",
    "        y1 = int(min(y_) * H) - 10\n",
    "        x2 = int(max(x_) * W) - 10\n",
    "        y2 = int(max(y_) * H) - 10\n",
    "\n",
    "        # Ensure data_aux has the correct size\n",
    "        expected_size = 7 * 6\n",
    "        if len(data_aux) < expected_size:\n",
    "            # Pad with zeros if too small\n",
    "            data_aux.extend([0] * (expected_size - len(data_aux)))\n",
    "        elif len(data_aux) > expected_size:\n",
    "            # Truncate if too large\n",
    "            data_aux = data_aux[:expected_size]\n",
    "\n",
    "        try:\n",
    "            # Reshape input data to match the model's expected input\n",
    "            input_data = np.asarray(data_aux).reshape(1, 42, 1)\n",
    "\n",
    "            # Predict the sign language character\n",
    "            prediction = model.predict(input_data)\n",
    "            predicted_index = np.argmax(prediction)\n",
    "            predicted_character = labels_dict[int(predicted_index)]\n",
    "            confidence = prediction[0][predicted_index] * 100\n",
    "\n",
    "            # Display the prediction and confidence on the frame\n",
    "            cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 0, 0), 4)\n",
    "            cv2.putText(frame, f'{predicted_character} ({confidence:.2f}%)', (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 1.3, (0, 0, 0), 3, cv2.LINE_AA)\n",
    "        except Exception as e:\n",
    "            print(f\"Error during prediction: {e}\")\n",
    "\n",
    "    cv2.imshow('frame', frame)\n",
    "    if cv2.waitKey(1) & 0xFF == ord('q'):\n",
    "        break\n",
    "\n",
    "cap.release()\n",
    "cv2.destroyAllWindows()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error during prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mCannot take the length of shape with unknown rank.\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n"
     ]
    }
   ],
   "source": [
    "import cv2\n",
    "import numpy as np\n",
    "import mediapipe as mp\n",
    "# from keras.models import load_model\n",
    "\n",
    "# Load the trained model\n",
    "# model = load_model('model.h5')\n",
    "\n",
    "# Define the labels dictionary\n",
    "labels_dict = {0: 'A', 1: 'B', 2: 'C', 3: 'D', 4: 'E', 5: 'F', 6: 'G', 7: 'H', 8: 'I', 9: 'J', 10: 'K', 11: 'L', 12: 'M', 13: 'N', 14: 'O', 15: 'P', 16: 'Q', 17: 'R', 18: 'S', 19: 'T', 20: 'U', 21: 'V', 22: 'W', 23: 'X'}\n",
    "\n",
    "# Initialize MediaPipe Hands\n",
    "mp_hands = mp.solutions.hands\n",
    "mp_drawing = mp.solutions.drawing_utils\n",
    "mp_drawing_styles = mp.solutions.drawing_styles\n",
    "\n",
    "hands = mp_hands.Hands(static_image_mode=True, min_detection_confidence=0.3)\n",
    "\n",
    "# Start video capture\n",
    "cap = cv2.VideoCapture(0)\n",
    "\n",
    "while True:\n",
    "    data_aux = []\n",
    "    x_ = []\n",
    "    y_ = []\n",
    "\n",
    "    ret, frame = cap.read()\n",
    "    if not ret:\n",
    "        print(\"Failed to capture image\")\n",
    "        break\n",
    "\n",
    "    H, W, _ = frame.shape\n",
    "    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)\n",
    "    results = hands.process(frame_rgb)\n",
    "\n",
    "    if results.multi_hand_landmarks:\n",
    "        for hand_landmarks in results.multi_hand_landmarks:\n",
    "            mp_drawing.draw_landmarks(\n",
    "                frame,  # image to draw\n",
    "                hand_landmarks,  # model output\n",
    "                mp_hands.HAND_CONNECTIONS,  # hand connections\n",
    "                mp_drawing_styles.get_default_hand_landmarks_style(),\n",
    "                mp_drawing_styles.get_default_hand_connections_style())\n",
    "\n",
    "            for i in range(len(hand_landmarks.landmark)):\n",
    "                x = hand_landmarks.landmark[i].x\n",
    "                y = hand_landmarks.landmark[i].y\n",
    "\n",
    "                x_.append(x)\n",
    "                y_.append(y)\n",
    "\n",
    "            for i in range(len(hand_landmarks.landmark)):\n",
    "                x = hand_landmarks.landmark[i].x\n",
    "                y = hand_landmarks.landmark[i].y\n",
    "                data_aux.append(x - min(x_))\n",
    "                data_aux.append(y - min(y_))\n",
    "\n",
    "        x1 = int(min(x_) * W) - 10\n",
    "        y1 = int(min(y_) * H) - 10\n",
    "        x2 = int(max(x_) * W) - 10\n",
    "        y2 = int(max(y_) * H) - 10\n",
    "\n",
    "        # Ensure data_aux has the correct size\n",
    "        expected_size = 7 * 6\n",
    "        if len(data_aux) < expected_size:\n",
    "            # Pad with zeros if too small\n",
    "            data_aux.extend([0] * (expected_size - len(data_aux)))\n",
    "        elif len(data_aux) > expected_size:\n",
    "            # Truncate if too large\n",
    "            data_aux = data_aux[:expected_size]\n",
    "\n",
    "        try:\n",
    "            # Resize input data to (7, 6, 1)\n",
    "            input_data = np.asarray(data_aux).reshape((7, 6, 1))\n",
    "\n",
    "            # Predict the sign language character\n",
    "            prediction = model.predict(np.array([input_data]))\n",
    "            predicted_index = np.argmax(prediction)\n",
    "            predicted_character = labels_dict[predicted_index]\n",
    "            confidence = prediction[0][predicted_index] * 100\n",
    "\n",
    "            # Debugging: Print raw prediction values\n",
    "            print(f\"Raw prediction: {prediction}\")\n",
    "            print(f\"Predicted character: {predicted_character}, Confidence: {confidence:.2f}%\")\n",
    "\n",
    "            # Display the prediction and confidence on the frame if confidence is above a threshold\n",
    "            if confidence > 50:  # Adjust the threshold as needed\n",
    "                cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 0, 0), 4)\n",
    "                cv2.putText(frame, f'{predicted_character} ({confidence:.2f}%)', (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 1.3, (0, 0, 0), 3, cv2.LINE_AA)\n",
    "        except Exception as e:\n",
    "            print(f\"Error during prediction: {e}\")\n",
    "\n",
    "    cv2.imshow('frame', frame)\n",
    "    if cv2.waitKey(1) & 0xFF == ord('q'):\n",
    "        break\n",
    "\n",
    "cap.release()\n",
    "cv2.destroyAllWindows()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "SLD_env",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
